### PR TITLE
Fix #18

### LINKED ISSUE #18: SPI/I2C keeps ref to FtInner, impossible to pass around once initialized
As implemented currently, the `SPI` / `I2C` / `OutputPin` structs all keep references to `Mutex<RefCell<FtInner<Device>>>`.

This makes it difficult / impossible to have `FtHal` inside a Box or RefCell or otherwise pass it around once SPI has been initialized.
(It is possible, but then each time one would need to access the SPI functions of `FtHal`, this would require re-initializing the SPI object with `Spi::new`, which is inefficient as it sends the MPSSE command each time).

Would it be possible to create a shallow `Spi::new` (and accordingly for the other structs) which basically becomes a no-op if SPI has already been initialized? Or are there other ideas how one could solve this?

My use case is that I need to share `FtHal` between two devices (e.g. using a shared pointer), each of which live on the Heap and need to have access to the SPI port...

### PR DESCRIPTION
**Pull request by newAM**

### CODE REVIEW

**Comment by KoviRobi** [comment]
Thank you, it works for me! [Also reassuring (for my Rust knowledge) that I started doing the same modifications in a local checkout, in removing the `'a` but didn't manage to solve the SpiBus]

**Comment by newAM** [comment]
> Thank you, it works for me!

Thanks for checking, I appreciate it!

I checked with my own projects and it works as well.

---

I'm not sure how I feel about changing `impl<'a, Device, E> eh1::spi::SpiDevice for SpiDevice<'a, Device>` to an implementation for the reference to avoid lifetime problems, `impl<'a, Device, E> eh1::spi::SpiDevice for &'a SpiDevice<Device>`, but this is for the embedded-hal 1.0.0 alpha traits, fine for now.

**Comment by newAM** [comment]
@geomatsi you want to take a look before I merge this?

**Comment by geomatsi** [comment]
Hi @newAM 

Feel free to merge ! I am busy with home stuff this fall, so I will not be up the task soon.

Regards,
Sergey

**Pull request merged**
